name: inspector
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.3.13-SNAPSHOT

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # cupertino_icons: ^1.0.0
  google_fonts: ^2.0.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  intl: ^0.17.0
  auto_route: ^0.6.7
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3
  flutter_slidable: ^0.5.7
  flutter_map: ^0.11.0
  #flutter_map:
  # git:
  #    url: https://github.com/ritikmishra/flutter_map.git
  #    ref: fix-listview-scrolling
  image_picker: ^0.7.0-nullsafety
  cached_network_image: ^3.0.0-nullsafety
  custom_switch_button: ^0.5.0
  provider: ^5.0.0-nullsafety.5
  dio: ^4.0.0-beta5
  objectdb: ^1.0.10+1
  date_range_picker: ^1.0.6
  local_auth: ^1.0.0-nullsafety.3
  async: ^2.4.2
  synchronized: ^3.0.0
  sqflite: ^2.0.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  url_launcher: ^6.0.2
  geolocator: ^7.0.1
  device_info: ^2.0.0
  uuid: ^3.0.0-nullsafety.0
  image: ^3.0.0-nullsafety.0
  connectivity: ^3.0.2
  flutter_webview_plugin: ^0.3.11
  json_annotation: ^4.0.0
  freezed_annotation: ^0.14.0
  geodesy: ^0.3.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.7
  json_serializable: ^4.0.2
  freezed: ^0.14.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - icons/
    - icons/Icon/
    - icons/Top_menu_icon/
    - icons/Menu_icon/
    - images/logo.png
    # - assets/map_tiles/
    # - assets/map_tiles/0/
    # - assets/map_tiles/0/0/
    # # - assets/map_tiles/1/
    # # - assets/map_tiles/1/0/
    # # - assets/map_tiles/1/1/
    # # - assets/map_tiles/10/
    # # - assets/map_tiles/10/616/
    # # - assets/map_tiles/10/617/
    # # - assets/map_tiles/10/618/
    # # - assets/map_tiles/10/619/
    # # - assets/map_tiles/10/620/
    # # - assets/map_tiles/10/621/
    # # - assets/map_tiles/11/
    # # - assets/map_tiles/11/1233/
    # # - assets/map_tiles/11/1234/
    # # - assets/map_tiles/11/1235/
    # # - assets/map_tiles/11/1236/
    # # - assets/map_tiles/11/1237/
    # # - assets/map_tiles/11/1238/
    # # - assets/map_tiles/11/1239/
    # # - assets/map_tiles/11/1240/
    # # - assets/map_tiles/11/1241/
    # # - assets/map_tiles/11/1242/
    # # - assets/map_tiles/12/
    # # - assets/map_tiles/12/2466/
    # # - assets/map_tiles/12/2467/
    # # - assets/map_tiles/12/2468/
    # # - assets/map_tiles/12/2469/
    # # - assets/map_tiles/12/2470/
    # # - assets/map_tiles/12/2471/
    # # - assets/map_tiles/12/2472/
    # # - assets/map_tiles/12/2473/
    # # - assets/map_tiles/12/2474/
    # # - assets/map_tiles/12/2475/
    # # - assets/map_tiles/12/2476/
    # # - assets/map_tiles/12/2477/
    # # - assets/map_tiles/12/2478/
    # # - assets/map_tiles/12/2479/
    # # - assets/map_tiles/12/2480/
    # # - assets/map_tiles/12/2481/
    # # - assets/map_tiles/12/2482/
    # # - assets/map_tiles/12/2483/
    # # - assets/map_tiles/12/2484/
    # # - assets/map_tiles/12/2485/
    # # - assets/map_tiles/13/
    # # - assets/map_tiles/13/4933/
    # # - assets/map_tiles/13/4934/
    # # - assets/map_tiles/13/4935/
    # # - assets/map_tiles/13/4936/
    # # - assets/map_tiles/13/4937/
    # # - assets/map_tiles/13/4938/
    # # - assets/map_tiles/13/4939/
    # # - assets/map_tiles/13/4940/
    # # - assets/map_tiles/13/4941/
    # # - assets/map_tiles/13/4942/
    # # - assets/map_tiles/13/4943/
    # # - assets/map_tiles/13/4944/
    # # - assets/map_tiles/13/4945/
    # # - assets/map_tiles/13/4946/
    # # - assets/map_tiles/13/4947/
    # # - assets/map_tiles/13/4948/
    # # - assets/map_tiles/13/4949/
    # # - assets/map_tiles/13/4950/
    # # - assets/map_tiles/13/4951/
    # # - assets/map_tiles/13/4952/
    # # - assets/map_tiles/13/4953/
    # # - assets/map_tiles/13/4954/
    # # - assets/map_tiles/13/4955/
    # # - assets/map_tiles/13/4956/
    # # - assets/map_tiles/13/4957/
    # # - assets/map_tiles/13/4958/
    # # - assets/map_tiles/13/4959/
    # # - assets/map_tiles/13/4960/
    # # - assets/map_tiles/13/4961/
    # # - assets/map_tiles/13/4962/
    # # - assets/map_tiles/13/4963/
    # # - assets/map_tiles/13/4964/
    # # - assets/map_tiles/13/4965/
    # # - assets/map_tiles/13/4966/
    # # - assets/map_tiles/13/4967/
    # # - assets/map_tiles/13/4968/
    # # - assets/map_tiles/13/4969/
    # # - assets/map_tiles/13/4970/
    # - assets/map_tiles/14/
    # # - assets/map_tiles/14/9866/
    # # - assets/map_tiles/14/9867/
    # - assets/map_tiles/14/9868/
    # - assets/map_tiles/14/9869/
    # - assets/map_tiles/14/9870/
    # - assets/map_tiles/14/9871/
    # - assets/map_tiles/14/9872/
    # - assets/map_tiles/14/9873/
    # - assets/map_tiles/14/9874/
    # - assets/map_tiles/14/9875/
    # - assets/map_tiles/14/9876/
    # - assets/map_tiles/14/9877/
    # - assets/map_tiles/14/9878/
    # - assets/map_tiles/14/9879/
    # - assets/map_tiles/14/9880/
    # - assets/map_tiles/14/9881/
    # - assets/map_tiles/14/9882/
    # - assets/map_tiles/14/9883/
    # - assets/map_tiles/14/9884/
    # - assets/map_tiles/14/9885/
    # - assets/map_tiles/14/9886/
    # - assets/map_tiles/14/9887/
    # - assets/map_tiles/14/9888/
    # - assets/map_tiles/14/9889/
    # - assets/map_tiles/14/9890/
    # - assets/map_tiles/14/9891/
    # - assets/map_tiles/14/9892/
    # - assets/map_tiles/14/9893/
    # - assets/map_tiles/14/9894/
    # - assets/map_tiles/14/9895/
    # - assets/map_tiles/14/9896/
    # - assets/map_tiles/14/9897/
    # - assets/map_tiles/14/9898/
    # - assets/map_tiles/14/9899/
    # - assets/map_tiles/14/9900/
    # - assets/map_tiles/14/9901/
    # - assets/map_tiles/14/9902/
    # - assets/map_tiles/14/9903/
    # - assets/map_tiles/14/9904/
    # - assets/map_tiles/14/9905/
    # - assets/map_tiles/14/9906/
    # - assets/map_tiles/14/9907/
    # - assets/map_tiles/14/9908/
    # - assets/map_tiles/14/9909/
    # - assets/map_tiles/14/9910/
    # - assets/map_tiles/14/9911/
    # - assets/map_tiles/14/9912/
    # - assets/map_tiles/14/9913/
    # - assets/map_tiles/14/9914/
    # - assets/map_tiles/14/9915/
    # - assets/map_tiles/14/9916/
    # - assets/map_tiles/14/9917/
    # - assets/map_tiles/14/9918/
    # - assets/map_tiles/14/9919/
    # # - assets/map_tiles/14/9920/
    # # - assets/map_tiles/14/9921/
    # # - assets/map_tiles/14/9922/
    # # - assets/map_tiles/14/9923/
    # # - assets/map_tiles/14/9924/
    # # - assets/map_tiles/14/9925/
    # # - assets/map_tiles/14/9926/
    # # - assets/map_tiles/14/9927/
    # # - assets/map_tiles/14/9928/
    # # - assets/map_tiles/14/9929/
    # # - assets/map_tiles/14/9930/
    # # - assets/map_tiles/14/9931/
    # # - assets/map_tiles/14/9932/
    # # - assets/map_tiles/14/9933/
    # # - assets/map_tiles/14/9934/
    # # - assets/map_tiles/14/9935/
    # # - assets/map_tiles/14/9936/
    # # - assets/map_tiles/14/9937/
    # # - assets/map_tiles/14/9938/
    # # - assets/map_tiles/14/9939/
    # # - assets/map_tiles/14/9940/
    # # - assets/map_tiles/2/
    # # - assets/map_tiles/2/0/
    # # - assets/map_tiles/2/1/
    # # - assets/map_tiles/2/2/
    # # - assets/map_tiles/2/3/
    # # - assets/map_tiles/3/
    # # - assets/map_tiles/3/0/
    # # - assets/map_tiles/3/1/
    # # - assets/map_tiles/3/2/
    # # - assets/map_tiles/3/3/
    # # - assets/map_tiles/3/4/
    # # - assets/map_tiles/3/5/
    # # - assets/map_tiles/3/6/
    # # - assets/map_tiles/3/7/
    # # - assets/map_tiles/4/
    # # - assets/map_tiles/4/0/
    # # - assets/map_tiles/4/1/
    # # - assets/map_tiles/4/10/
    # # - assets/map_tiles/4/11/
    # # - assets/map_tiles/4/12/
    # # - assets/map_tiles/4/13/
    # # - assets/map_tiles/4/14/
    # # - assets/map_tiles/4/15/
    # # - assets/map_tiles/4/2/
    # # - assets/map_tiles/4/3/
    # # - assets/map_tiles/4/4/
    # # - assets/map_tiles/4/5/
    # # - assets/map_tiles/4/6/
    # # - assets/map_tiles/4/7/
    # # - assets/map_tiles/4/8/
    # # - assets/map_tiles/4/9/
    # # - assets/map_tiles/5/
    # # - assets/map_tiles/5/0/
    # # - assets/map_tiles/5/1/
    # # - assets/map_tiles/5/10/
    # # - assets/map_tiles/5/11/
    # # - assets/map_tiles/5/12/
    # # - assets/map_tiles/5/13/
    # # - assets/map_tiles/5/14/
    # # - assets/map_tiles/5/15/
    # # - assets/map_tiles/5/16/
    # # - assets/map_tiles/5/17/
    # # - assets/map_tiles/5/18/
    # # - assets/map_tiles/5/19/
    # # - assets/map_tiles/5/2/
    # # - assets/map_tiles/5/20/
    # # - assets/map_tiles/5/21/
    # # - assets/map_tiles/5/22/
    # # - assets/map_tiles/5/23/
    # # - assets/map_tiles/5/24/
    # # - assets/map_tiles/5/25/
    # # - assets/map_tiles/5/26/
    # # - assets/map_tiles/5/27/
    # # - assets/map_tiles/5/28/
    # # - assets/map_tiles/5/29/
    # # - assets/map_tiles/5/3/
    # # - assets/map_tiles/5/30/
    # # - assets/map_tiles/5/31/
    # # - assets/map_tiles/5/4/
    # # - assets/map_tiles/5/5/
    # # - assets/map_tiles/5/6/
    # # - assets/map_tiles/5/7/
    # # - assets/map_tiles/5/8/
    # # - assets/map_tiles/5/9/
    # # - assets/map_tiles/6/
    # # - assets/map_tiles/6/38/
    # # - assets/map_tiles/7/
    # # - assets/map_tiles/7/77/
    # # - assets/map_tiles/8/
    # # - assets/map_tiles/8/154/
    # # - assets/map_tiles/8/155/
    # # - assets/map_tiles/9/
    # # - assets/map_tiles/9/308/
    # # - assets/map_tiles/9/309/
    # # - assets/map_tiles/9/310/
